### ISSUE TITLE
Rewrite it in Rust

### ISSUE THREAD

**Issue by InaneBob** [bunkerchan/dynchan#1]

**Comment by jlettman** [comment]
If I'm going to write low-level code, it best crash in a horrible fashion. It keeps you on your toes.

**Comment by SpaceDustTeapot** [comment]
Either contribute or trole elsewhere @inanebob

**Comment by InaneBob** [comment]
I can't contribute until you adopted a Code of Conduct.
Read this: http://contributor-covenant.org/

**Comment by SpaceDustTeapot** [comment]
No.

**Comment by jlettman** [comment]
Despite the obvious trolling, I do find it interesting how that is placed into projects that are just code. 
It's just software. Why can't people just calm down. It's not some kind of massive community like Facebook where posting shocking images is a possibility.

The most important thing for people to bundle down and hang onto for the rest of their lives is that the universe doesn't care. A nearby star, many light years away,  could explode and strip our atmosphere with just it's radiation. That star doesn't care how you feel about getting torched.

If somebody hurts your feelings in an open source project that is a software repository, remember that star.

**Comment by jlettman** [comment]
anyways 10/10 meem

**Comment by InaneBob** [comment]
\>implying i am memeing
why dont you guys want a coc? are you racists?

**Comment by jlettman** [comment]
I would certainly hope not and I don't want to evoke the entire "I have X, Y, and Z friends". Suffice to say, I don't think anybody here has any reservations towards any ethnic group.

**Comment by InaneBob** [comment]
then why won't you adopt a coc?

**Comment by jlettman** [comment]
It would be feasible if this is a large project; however, because this is at the least two developers and at the most two developers and @InaneBob. I can't possibly imagine community guidelines for something so insignificant. 

As much as I would like for Dynchan to be a project where that would be reasonable, I know the reality is that this is a tiny little imageboard project that @SpaceDustTeapot and myself are hacking together.

**Comment by jlettman** [comment]
@InaneBob 
What is your opinion of the [Code of Conduct present in the "Trend" project here](https://github.com/bunkerchan/trend/blob/master/CODE_OF_CONDUCT.md)?

**Comment by InaneBob** [comment]
> Use common sense
but people are different. common sense means something different for everybody.
racists for example think that racism is ok. (which it isn't!!!)

**Comment by jlettman** [comment]
Yes, but because this is a centralized totalitarian governing body, speech that would be against the GitHub Terms of Use would be eliminated with the iron might of the remove button.

**Comment by InaneBob** [comment]
alright this is acceptable. i now feel comfortable to contribute rust code.

**Comment by jlettman** [comment]
yeah, but remember, although GitHub got rid of their magic meritocracy carpet...
